### ISSUE TITLE
MissingMethodException in AutofacSerilogIntegration.ContextualLoggingModule.AttachToComponentRegistration

### ISSUE THREAD

**Issue by melvinduc** [nblumhardt/autofac-serilog-integration#45]
This exception is introduced since version 3.0.0. In version 2.1.0. it is working.

**Steps to reproduce**
Create a new ASP.NET Core Web API application. 
Add nuget packages

```
    <PackageReference Include="Autofac" Version="6.0.0" />
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="7.1.0" />
    <PackageReference Include="AutofacSerilogIntegration" Version="4.0.0" />
    <PackageReference Include="Serilog" Version="2.10.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />
```

**Modify Program.cs**
```
public static void Main(string[] args)
        {
            Log.Logger = new LoggerConfiguration()
                .WriteTo.Console()
                .CreateLogger();

            Log.Information("Hello World!");
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .UseServiceProviderFactory(new AutofacServiceProviderFactory())
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
```

**Modify Startup.cs**
```
public void ConfigureContainer(ContainerBuilder builder)
        {
            builder.RegisterLogger();
        }
```

Running the application will result in 
```
Unhandled exception. System.MissingMethodException: Method not found: 'Void Autofac.Core.IComponentRegistration.add_Preparing(System.EventHandler`1<Autofac.Core.PreparingEventArgs>)'.
   at AutofacSerilogIntegration.ContextualLoggingModule.AttachToComponentRegistration(IComponentRegistryBuilder componentRegistry, IComponentRegistration registration)
   at Autofac.Module.<AttachToRegistrations>b__4_0(Object sender, ComponentRegisteredEventArgs e)
   at Autofac.Core.Registration.ComponentRegistryBuilder.add_Registered(EventHandler`1 value)
   at Autofac.Module.AttachToRegistrations(IComponentRegistryBuilder componentRegistry)
   at Autofac.Module.Configure(IComponentRegistryBuilder componentRegistry)
   at Autofac.ContainerBuilder.Build(IComponentRegistryBuilder componentRegistry, Boolean excludeDefaultModules)
   at Autofac.ContainerBuilder.Build(ContainerBuildOptions options)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProviderFactory.CreateServiceProvider(ContainerBuilder containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
```

When I downgrade the AutfacSerilogIntegration to version 2.1.0 it is working. Am I missing something or is this a bug?

**Comment by nblumhardt** [comment]
Hi! You need version 5.0 of the package in order to work with Autofac 6; just published: https://github.com/nblumhardt/autofac-serilog-integration/pull/43

**Comment by melvinduc** [comment]
Thanks!
